# Generated by Django 3.2.4 on 2023-02-27 14:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('globalContactData', '0002_globalcontactmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalcontactmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=False),
        ),
    ]
