# Generated by Django 3.2.4 on 2023-02-27 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('globalContactData', '0003_alter_globalcontactmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalcontactmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='globalcontactmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_contact_database', to=settings.AUTH_USER_MODEL),
        ),
    ]
