# Generated by Django 4.1.7 on 2023-02-23 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortFolioImageVesions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_field', models.ImageField(upload_to='', verbose_name='portfolio_photo')),
                ('original_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_image', to='uploader.originalimage')),
            ],
        ),
        migrations.CreateModel(
            name='LogoImageVersions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_field', models.ImageField(upload_to='', verbose_name='logo_photo')),
                ('original_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logo_image', to='uploader.originalimage')),
            ],
        ),
        migrations.CreateModel(
            name='LandscapeImageVesions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landscape_field', models.ImageField(upload_to='', verbose_name='landscape_photo')),
                ('original_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landscape_image', to='uploader.originalimage')),
            ],
        ),
    ]
